[package]
name = "audiotest"
version = "0.1.0"
authors = ["andr3"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.13.1"
num-complex = "0.3.1"
image = "0.23.12"
